config/routes.rb
Robocent::Application.routes.draw do

  post "welcome-pop-up-submit" => 'dashboard#welcome_pop_up_submit', :as => :welcome_pop_up_submit

  resources :dnc, :only => [:index, :create, :destroy]

  match 'inbox-support'       => 'support#inbox',       :as => :inbox_support
  match 'send-a-call-support' => 'support#send_a_call', :as => :send_a_call_support
  match 'send-a-text-support' => 'support#send_a_text', :as => :send_a_text_support
  match 'dashboard-support'   => 'support#contacts',    :as => :contacts_support
  match 'support'             => 'support#index',       :as => :dashboard_support

  resources :password_resets, :except => [:index, :destroy]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "find-new-recording" => 'recordings#find_new_recording'
  match "replay"          => 'recordings#replay', :as => :replay
  match "save-or-record"  => 'recordings#save_or_record', :as => :save_or_record

  resources :incoming_calls

  resources :recordings do
    member do
      get :play
    end
  end

  match 'send-call'      => 'calls#new',            :as => :send_call
  match 'send-test-call' => 'calls#send_test_call', :as => :send_test_call

  resources :calls

  post "notifications/adaptive_ipn" => "notifications#adaptive_ipn"

  get "inbox"   => "sms_messages#inbox", :as => :inbox
  get "inbox-read" => "sms_messages#inbox_read"
  get "start-conversation" => 'sms_messages#start_conversation', :as => :start_conversation

  resources :sms_messages

  resources :text_messages, :only => [:show, :create] do
    member do
      get :send_text_succeeded_numbers
      get :send_text_errors
    end
  end

  #
  # Text
  #
  match 'send-a-test'         => 'text_messages#send_a_test', :as => :send_a_test
  match 'send-text'           => 'text_messages#new',         :as => :send_text

  put   "migrate"             => "subscriptions#migrate",   :as => :migrate
  match "migration"           => "subscriptions#migration", :as => :migration

  post 'stripe-webhook'       => 'stripe_webhook#create'

  put   'update-billing/:id'  => 'billing#update',       :as => :update_billing
  match 'edit-billing/:id'    => 'billing#edit',         :as => :edit_billing
  post  'fund-account'        => 'billing#fund_account', :as => :fund_account
  get   'billing'             => 'billing#index',           :as => :billing
  post  'billing'             => 'billing#create',          :as => :create_billing

  resources :imports do
    collection do
      get :save_s3_file_path
    end
    member do
      get :map_column
      match :insert_into_db
    end
  end

  resources :contacts

  resources :lists do
    member do
      get :export_contacts
    end
    collection do
      match :check_validation
    end
  end

  #
  # Dashboard
  #
  match 'profile'               => 'dashboard#profile',           :as => :profile
  match 'dashboard'             => 'dashboard#index',             :as => :dashboard

  #
  # user sessions
  #
  match 'login'                 => 'user_sessions#new',           :as => :login
  match 'logout'                => 'user_sessions#destroy',       :as => :logout

  resources :user_sessions, :only => [:create]

  #
  # registration
  #
  get   'twilionumbers/:code'      => 'users#twilionumbers',  :as => :twilionumbers
  match 'register/activate/:token' => 'users#activate',       :as => :activate

  put 'update-password'    => 'users#update_password',   :as => :update_password

  resources :users, :except => [:index, :show, :destroy]
  
  #
  # public pages
  #
  match "email-code"       => 'publics#email_code'
  match "email"       => 'publics#promo_email', :as => :promo_email
 
  match "smsterms"    => "publics#sms_terms", :as => :sms_terms
  match "smsprivacy"  => "publics#sms_privacy", :as => :sms_privacy
  match "terms"       => "publics#terms",      :as => "terms"
  match "privacy-policy" => "publics#privacy_policy", :as => :privacy_policy
  match 'contact-us-submit' => "publics#contact_us_submit" , :as => :contact_us_submit
  match "contact-us"  => "publics#contact",    :as => "contact_us"
  match 'solutions'   => "publics#solutions",  :as => "solutions"
  match 'residential-communities'   => "publics#residential_communities",  :as => "residential_communities"

  root :to => 'publics#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :keyword, :name, :number_of_contacts, :type_of_list, :user_id,
    :shortcode_keyword, :greeting

  belongs_to  :user
  has_many    :imports,  :dependent => :destroy
  has_many    :contacts, :dependent => :destroy

  validate :name_uniqueness
  validate :keyword_uniqueness
  validate :shortcode_keyword_max, :on => :create

  validates :name, :presence => true
  validates :type_of_list, :presence => true
  validates :shortcode_keyword, :uniqueness => true, :if => Proc.new{|list| list.shortcode_keyword.present? }

  before_save{|l| l.shortcode_keyword = nil if l.shortcode_keyword.blank? }

  def name_uniqueness
    if self.new_record? and List.find_by_user_id_and_name_and_type_of_list(user.id, name, type_of_list).present?
      errors.add(:name, "has already been taken")
    elsif List.find(:first, :conditions => ["lists.id <> ? and lists.user_id = ? and lists.name = ? and lists.type_of_list = ?", self.id, user.id, self.name, self.type_of_list]).present?
      errors.add(:name, "has already been taken")
    end
  end

  def keyword_uniqueness
    if self.keyword.present?
      if self.new_record? and List.find_by_user_id_and_keyword(user.id, keyword).present?
        errors.add(:keyword, "has already been taken")
      elsif List.find(:first, :conditions => ["lists.id <> ? and lists.user_id = ? and lists.keyword = ?", id, user.id, self.keyword]).present?
        errors.add(:keyword, "has already been taken")
      end
    end
  end

  def shortcode_keyword_max
    max_keywords = self.user.subscription.plan.max_keywords
    total_keywords = self.user.lists.count(:all, :conditions => ["shortcode_keyword is not NULL"])
    if total_keywords >= max_keywords
      self.shortcode_keyword = nil
    end
  end

  scope :sum_number_of_contacts, :select => "SUM(number_of_contacts) as total"
  scope :by_call, :conditions => "type_of_list = 'call'"
  scope :by_text, :conditions => "type_of_list = 'text'"

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :require_login
  load_and_authorize_resource

  layout 'dashboard'

  def show
    session[:list_contacts] = true
    @list = List.find(params[:id])
    @contacts = @list.contacts
    @user = current_user
    @dnc_list = @user.dnc.map{|dnc| dnc.phone}
  end

  def new
    session[:referer] = request.referer
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = current_user.lists.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to session[:referer].present? ? session[:referer] : contacts_path }
        format.js
      else
        format.html { render :action => :new }
        format.js
      end
    end
  end

  def check_validation
    @error = {}
    if params[:list_id].present?
      @list = List.find(params[:list_id])
      list = List.find(:first, :conditions => ["lists.id <> ? and lists.user_id = ? and lists.name = ? and lists.type_of_list = ?", @list.id, current_user.id, params[:list][:name], @list.type_of_list])
      @error[:name] = "You have already used this list name for list type #{@list.type_of_list} !" if list.present?
      list1 = List.find(:first, :conditions => ["lists.id <> ? and lists.user_id = ? and lists.keyword = ?", @list.id, current_user.id, params[:list][:keyword]]) if params[:list][:keyword].present?
      @error[:keyword] = "You have already used this keyword!" if list1.present?
      list2 = List.find(:first, :conditions => ["lists.id <> ? and lists.shortcode_keyword = ?", @list.id, params[:list][:shortcode_keyword]]) if params[:list][:shortcode_keyword].present?
      @error[:shortcode_keyword]= "This keyword is not available!" if list2.present?
    else
      @list = current_user.lists.new(params[:list])
      list = List.find_by_user_id_and_name_and_type_of_list(current_user.id, @list.name, @list.type_of_list)
      @error[:name] = "You have already used this list name for list type #{@list.type_of_list} !" if list.present?
      list1 = List.find_by_user_id_and_keyword(current_user.id, @list.keyword) if @list.keyword.present?
      @error[:keyword] = "You have already used this keyword!" if list1.present?
      list2 = List.find_by_shortcode_keyword(@list.shortcode_keyword) if @list.shortcode_keyword.present?
      @error[:shortcode_keyword]= "This keyword is not available!" if list2.present?
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to contacts_path, notice: 'List was successfully updated.' }
        format.js
      else
        format.html { render :action => :edit }
        format.js
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.js
    end
  end

  def export_contacts
    @contacts = Contact.where(:list_id => params[:id]).includes(:list)
    respond_to do |format|
      format.csv { send_data @contacts.to_csv }
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<div class="g_12">
  <div class="widget_contents noPadding">
    <%= form_for(@list ||= List.new, :html => {:class => "list_form"}) do |f| %>
      <%= hidden_field_tag :list_id, @list.id unless @list.new_record? %>
      <%= hidden_field_tag "page_from", controller.controller_name + "/" + controller.action_name %>
      <div class="line_grid">
        <div class="g_3">
          <span class="label">List Name<span class="must">*</span></span>
        </div>
        <div class="g_9">
          <div class="filed_error" id="error_list_name"></div>
          <%= f.text_field :name, :class => "simple_field", :required => true %>
        </div>
      </div>
      <% if @list.new_record? %>
        <div class="line_grid">
          <div class="g_3">
            <span class="label">Type of List<span class="must">*</span></span>
          </div>
          <div class="g_9">
            <%= f.select :type_of_list, [['Text', 'text'],['Call', 'call']], {}, :class => "simple_form", :required => true %>
          </div>
        </div>
      <% end %>

      <% if @list.new_record? or @list.type_of_list == "text" %>
        <% if current_user.twilio_phone_number.present? %>
          <% @greeting = true %>
          <div class="line_grid" id="row-keyword">
            <div class="g_3">
              <span class="label">Keyword</span>
            </div>
            <div class="g_9">
              <div class="filed_error" id="error_list_keyword"></div>
              <%= f.text_field :keyword, :class => "simple_field" %>
              <div class="field_notice">
                When subscribers will text this keyword to
                <%= formatted_number current_user.twilio_phone_number.phone_number %>,
                they will automatically join your list.
              </div>
            </div>
          </div>
        <% end %>
        <% if @list.shortcode_keyword or current_user.allowed_to_create_keyword? %>
          <% @greeting = true %>
          <div class="line_grid" id="row-shortcode-keyword">
            <div class="g_3">
              <span class="label">Keyword for ShortCode</span>
            </div>
            <div class="g_9">
              <div class="filed_error" id="error_list_shortcode_keyword"></div>
              <%= f.text_field :shortcode_keyword, :class => "simple_field" %>
              <div class="field_notice">
                When subscribers will text this keyword to 47543, they will automatically join your list.
              </div>
            </div>
          </div>
        <% end %>
        <% if @greeting.present? %>
          <div class="line_grid" id="row-greeting">
            <div class="g_3">
              <span class="label">Intro Greeting Text</span>
            </div>
            <div class="g_9">
              <div class="filed_error" id="error_list_shortcode_keyword"></div>
              <%= f.text_field :greeting, :class => "simple_field" %>
              <div class="field_notice">
              </div>
            </div>
          </div>
        <% end %>
      <% end %>

      <div class="line_grid">
        <div class="g_3"></div>
        <div class="g_3">
          <%= f.submit :class => "submitIt simple_buttons" %>
        </div>
        <div class="g_6">
          <div class="ajax-loading" style="display:none">
            <%= image_tag("dashboard/Icons/Load/load-8.gif") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/lists/_list_tiny.html.erb
<tr id="list_row_<%= list.id %>">
  <td><%= list.name %></td>
  <td><%= list.type_of_list.capitalize %></td>
  <td><%= list.number_of_contacts %></td>
  <td><%= list.keyword %></td>
  <td>
    <%= list.shortcode_keyword %>
  </td>
  <td align="center">
    <%= link_to "View", list, :class => "submitIt simple_buttons"  %>
  </td>
  <td>
    <div style="float: left">
      <%= link_to "Edit", edit_list_path(list), :class => "simple_buttons", :style => "padding: 0 10px 0 10px;" %>
      / </div>
    <%= form_tag list_url(list), :method => "delete", :id => "list_delete_link", :style => "float:left;margin-left:5px;" do %>
      <%= submit_tag "Delete", :class => "submitIt simple_buttons" %>
    <% end %>
    <div class="clear"></div>
  </td>
</tr>

app/views/lists/check_validation.js.erb
$(".ajax-loading").hide();
<% if @error[:name].present?  %>
  $("#error_list_name").removeClass("ok");
  $("#error_list_name").html("<%= @error[:name] %>");
<% elsif @list.name.present? %>
  $("#error_list_name").html("");
  $("#error_list_name").addClass("ok");
<% else %>
  $("#error_list_name").removeClass("ok");
  $("#error_list_name").html("");
<% end %>

<% if @error[:keyword].present?  %>
  $("#error_list_keyword").removeClass("ok");
  $("#error_list_keyword").html("<%= @error[:keyword] %>");
<% elsif @list.keyword.present? or params[:list][:keyword].present? %>
  $("#error_list_keyword").html("");
  $("#error_list_keyword").addClass("ok");
<% else %>
  $("#error_list_keyword").removeClass("ok");
  $("#error_list_keyword").html("");
<% end %>

<% if @error[:shortcode_keyword].present?  %>
  $("#error_list_shortcode_keyword").removeClass("ok");
  $("#error_list_shortcode_keyword").html("<%= @error[:shortcode_keyword] %>");
<% elsif @list.shortcode_keyword.present? or params[:list][:shortcode_keyword].present? %>
  $("#error_list_shortcode_keyword").html("");
  $("#error_list_shortcode_keyword").addClass("ok");
<% else %>
  $("#error_list_shortcode_keyword").removeClass("ok");
  $("#error_list_shortcode_keyword").html("");
<% end %>

<% if @error.size == 0 and @list.name.present? %>
  $("form.list_form input[type=submit]").attr("disabled", false);
<% else %>
  $("form.list_form input[type=submit]").attr("disabled", true);
<% end %>

app/views/lists/create.js.erb
<% if params[:page_from] == "contacts/new" %>
  $("#contact_list").html("<%= escape_javascript(render :partial => "contacts/select_list").html_safe %>");
  $("#import_form_contact_list").html("<%= escape_javascript(render :partial => "imports/select_list").html_safe %>");
  $("select#contact_list_id").uniform();
  $("select#import_list_id").uniform();
<% else %>
  <% unless @list.new_record? %>
    $("#no-records-row").remove();
    $("#contact-lists-table tbody").prepend("<%= escape_javascript(render :partial => "list_tiny", :locals => {:list => @list}).html_safe %>");
  <% end %>
  $("#contact-lists-table .ajax-loading").hide();
<% end %>

app/views/lists/destroy.js.erb
<% if @list.present? %>
$("#contact-lists-table .ajax-loading").hide();
$("#contact-lists-table tbody tr#list_row_<%= @list.id %>").remove();
<% end %>

app/views/lists/edit.html.erb
<div class="g_12">
  <div class="g_6 contents_header">
    <h3 class="i_16_ui tab_label">Edit List</h3>
  </div>

  <div class="g_12 separator"><span></span></div>

  <% if @list.errors.any? %>
    <div class="g_12">
      <div class="form-error">
        Please correct these <%= pluralize(@list.errors.full_messages.count, "error") %>:<br/>
        <% @list.errors.full_messages.each do |msg| %>
          * <%= msg %><br/>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= render "form" %>

</div>

app/views/lists/new.html.erb
<div class="g_6 contents_header">
  <h3 class="i_16_ui tab_label">New List</h3>
</div>
<div class="g_2"></div>
<div class="g_2">
  <%= link_to "Add Contacts", new_contact_path, :class => "simple_buttons contact-button", :id => "new_list_link_1" %>
</div>
<div class="g_2">
  <%= link_to "Back to Lists", contacts_path, :class => "simple_buttons contact-button" %>
</div>

<div class="g_12 separator"><span></span></div>

<div class="g_12" id="http_form">
  <% if @list.errors.any? %>
    <div class="g_12">
      <div class="form-error">
        Please correct these <%= pluralize(@list.errors.full_messages.count, "error") %>:<br/>
        <% @list.errors.full_messages.each do |msg| %>
          * <%= msg %><br/>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= render "form" %>
</div>
<div id="dialog" title="Create New List">
  <div class="dialog">
    <%= render "lists/form" %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="g_6 contents_header">
  <h3 class="i_16_ui tab_label">Contacts (<%= @list.name %>)</h3>
</div>
<div class="g_2"></div>
<div class="g_2">
  <%= link_to "Back to Contacts", contacts_path, :class => "simple_buttons contact-button" %>
</div>
<div class="g_2">
  <%= link_to "Add Contacts", new_contact_path, :class => "simple_buttons contact-button" %>
</div>

<div class="g_12 separator"><span></span></div>

<div class="g_12">
  <div class="widget_header wwOptions">
    <h4 class="widget_header_title wwIcon i_16_tables">
      View and Edit Contacts
    </h4>
  </div>
  <div class="widget_contents noPadding">
    <table class="tables" id="contacts-table">
      <thead>
      <th>Phone</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>
        <div class="ajax-loading" style="display:none">
          <%= image_tag("dashboard/Icons/Load/load-8.gif") %>
        </div>
      </th>
      </thead>
      <tbody>
        <% if @contacts.present? %>
          <% @contacts.each do |contact| %>
            <%= render :partial => "contacts/contact_tiny", :locals => {:contact => contact} %>
          <% end %>
        <tr>
          <td colspan="6" align="center">
              <%= link_to "Export List as CSV", export_contacts_list_path(@list, :format => "csv"), :style => "color:#696969" %>
          </td>
        </tr>
        <% else %>
          <tr>
            <td colspan="5" style="text-align:center">
              No Records Found.
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/lists/update.js.erb
<% if @list.present? %>
$("#contact-lists-table .ajax-loading").hide();
$("#contact-lists-table tbody tr#list_row_<%= @list.id %>").replaceWith("<%= escape_javascript(render :partial => "list_tiny", :locals => {:list => @list}).html_safe %>");
<% end %>