config/routes.rb
Robocent::Application.routes.draw do

  post "welcome-pop-up-submit" => 'dashboard#welcome_pop_up_submit', :as => :welcome_pop_up_submit

  resources :dnc, :only => [:index, :create, :destroy]

  match 'inbox-support'       => 'support#inbox',       :as => :inbox_support
  match 'send-a-call-support' => 'support#send_a_call', :as => :send_a_call_support
  match 'send-a-text-support' => 'support#send_a_text', :as => :send_a_text_support
  match 'dashboard-support'   => 'support#contacts',    :as => :contacts_support
  match 'support'             => 'support#index',       :as => :dashboard_support

  resources :password_resets, :except => [:index, :destroy]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "find-new-recording" => 'recordings#find_new_recording'
  match "replay"          => 'recordings#replay', :as => :replay
  match "save-or-record"  => 'recordings#save_or_record', :as => :save_or_record

  resources :incoming_calls

  resources :recordings do
    member do
      get :play
    end
  end

  match 'send-call'      => 'calls#new',            :as => :send_call
  match 'send-test-call' => 'calls#send_test_call', :as => :send_test_call

  resources :calls

  post "notifications/adaptive_ipn" => "notifications#adaptive_ipn"

  get "inbox"   => "sms_messages#inbox", :as => :inbox
  get "inbox-read" => "sms_messages#inbox_read"
  get "start-conversation" => 'sms_messages#start_conversation', :as => :start_conversation

  resources :sms_messages

  resources :text_messages, :only => [:show, :create] do
    member do
      get :send_text_succeeded_numbers
      get :send_text_errors
    end
  end

  #
  # Text
  #
  match 'send-a-test'         => 'text_messages#send_a_test', :as => :send_a_test
  match 'send-text'           => 'text_messages#new',         :as => :send_text

  put   "migrate"             => "subscriptions#migrate",   :as => :migrate
  match "migration"           => "subscriptions#migration", :as => :migration

  post 'stripe-webhook'       => 'stripe_webhook#create'

  put   'update-billing/:id'  => 'billing#update',       :as => :update_billing
  match 'edit-billing/:id'    => 'billing#edit',         :as => :edit_billing
  post  'fund-account'        => 'billing#fund_account', :as => :fund_account
  get   'billing'             => 'billing#index',           :as => :billing
  post  'billing'             => 'billing#create',          :as => :create_billing

  resources :imports do
    collection do
      get :save_s3_file_path
    end
    member do
      get :map_column
      match :insert_into_db
    end
  end

  resources :contacts

  resources :lists do
    member do
      get :export_contacts
    end
    collection do
      match :check_validation
    end
  end

  #
  # Dashboard
  #
  match 'profile'               => 'dashboard#profile',           :as => :profile
  match 'dashboard'             => 'dashboard#index',             :as => :dashboard

  #
  # user sessions
  #
  match 'login'                 => 'user_sessions#new',           :as => :login
  match 'logout'                => 'user_sessions#destroy',       :as => :logout

  resources :user_sessions, :only => [:create]

  #
  # registration
  #
  get   'twilionumbers/:code'      => 'users#twilionumbers',  :as => :twilionumbers
  match 'register/activate/:token' => 'users#activate',       :as => :activate

  put 'update-password'    => 'users#update_password',   :as => :update_password

  resources :users, :except => [:index, :show, :destroy]
  
  #
  # public pages
  #
  match "email-code"       => 'publics#email_code'
  match "email"       => 'publics#promo_email', :as => :promo_email
 
  match "smsterms"    => "publics#sms_terms", :as => :sms_terms
  match "smsprivacy"  => "publics#sms_privacy", :as => :sms_privacy
  match "terms"       => "publics#terms",      :as => "terms"
  match "privacy-policy" => "publics#privacy_policy", :as => :privacy_policy
  match 'contact-us-submit' => "publics#contact_us_submit" , :as => :contact_us_submit
  match "contact-us"  => "publics#contact",    :as => "contact_us"
  match 'solutions'   => "publics#solutions",  :as => "solutions"
  match 'residential-communities'   => "publics#residential_communities",  :as => "residential_communities"

  root :to => 'publics#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_login

  layout 'dashboard'

  def index
    @total_contacts_count = current_user.lists.sum_number_of_contacts.first.total.to_i
    @call_contacts_count = current_user.lists.sum_number_of_contacts.by_call.first.total.to_i
    @text_contacts_count = current_user.lists.sum_number_of_contacts.by_text.first.total.to_i
    @price_per_call_or_text = current_user.subscription.plan.price_per_call_or_text

    @total_text_or_call_can_send = ((current_user.current_balance * 100.0) / @price_per_call_or_text).to_i

    @text_messages = current_user.text_messages
    @calls = current_user.calls
  end

  def profile
    @user = current_user
  end

  def welcome_pop_up_submit
    if params[:list].present?
      @list = current_user.lists.new(params[:list])
      @list.type_of_list = "text"
      @list_create = true if @list.save
    end

    if current_user.subscription.plan.recurring and params[:twilio_phone_number].present?
      @tpn = current_user.build_twilio_phone_number(params[:twilio_phone_number])
      @number_create = true if @tpn.save
    end

    notice = (@list_create.present? or @number_create.present?) ? "Successfully Saved Settings!" : ""
    redirect_to dashboard_path, :notice => notice
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_add_keyword_phone_number.html.erb
<div id="set_keyword_and_phone_number_form" title="Welcome to RoboCent!">
  <div class="g_12" style="background: white">
    <div class="widget_contents noPadding">
      <%= form_tag welcome_pop_up_submit_path, :method => :post, :id => "welcome-pop-up-form" do %>
        <div class="line_grid">
          <div class="g_12 widget_header_title">
            Please create your first Contact List and the keyword people can text to 47543 to
            join the list. You may create and manage your lists and keywords on the contacts
            tab.
          </div>
        </div>

        <%= fields_for List.new do |l| %>
          <div class="line_grid">
            <div class="g_2">
              <span class="label">List Name : </span>
            </div>
            <div class="g_4">
              <div class="filed_error" id="error_list_name"></div>
              <%= l.text_field :name, :class => "simple_field" %>
            </div>
            <div class="g_2">
              <span class="label">Keyword : </span>
            </div>
            <div class="g_4">
              <div class="filed_error" id="error_list_shortcode_keyword"></div>
              <%= l.text_field :shortcode_keyword, :class => "simple_field" %>
            </div>
          </div>
        <% end %>

        <% if current_user.subscription.plan.recurring %>
          <div class="line_grid">
            <div class="g_12 widget_header_title ">
              You may also create a regular phone number in any area code to send text and
              calls from. To create a regular phone number, please enter the area code below.
              You may create and manage phone numbers on the profile tab.
            </div>
          </div>

          <%= fields_for TwilioPhoneNumber.new do |t| %>
            <div class="line_grid">
              <div class="g_2">
                <span class="label">Area Code : </span>
              </div>
              <div class="g_2">
                <div class="filed_error" id="error_list_name"></div>
                <%= t.text_field :area_code, :maxlength => "3", :class => "simple_field" %>
              </div>
              <div class="g_2">
                <div id="ajax-loader" style="width: 33px;">
                  <%= image_tag("loading.gif", :style => "display:none") %>
                </div>
              </div>
              <div class="g_2">
                <span class="label">
                  Select Number :
                </span>
              </div>
              <div class="g_4">
                <div class="filed_error" id="error_list_shortcode_keyword"></div>
                <span id="twilio_phone_number_select">
                  <%= t.select :phone_number, "", {:prompt => "Select Number" }, :class => "simple_form" %>
                </span>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="line_grid">
            <div class="g_12 widget_header_title ">
              If you want to create a regular phone number in any area code to send text and
              calls from. You have to upgrade your account to Basic or Advanced from billing tab.
              Then you may create and manage phone numbers on the profile tab.
            </div>
          </div>
        <% end %>

        <div class="line_grid">
          <div class="g_4"></div>
          <div class="g_2">
            <%= submit_tag "Save Settings", :class => "submitIt simple_buttons" %>
          </div>
          <div class="g_2">
            <div class="ajax-loading" style="display:none">
              <%= image_tag("dashboard/Icons/Load/load-8.gif") %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $("#set_keyword_and_phone_number_form").dialog({
      closeOnEscape: false,
      autoOpen : true,
      resizable: false,
      draggable: false,
      modal : true,
      height: 'auto',
      width : 800,
      position: 'center',
      overlay: {
        opacity: 0.5
      }
    });

    $("#list_shortcode_keyword, #list_name").live("keyup", function(){
      delay(function(){
        if(typeof window.xhr != 'undefined'){
          window.xhr.abort();
        }
        $("#welcome-pop-up-form .ajax-loading").show();
        var form = $("#welcome-pop-up-form");
        var action = '/lists/check_validation'
        window.xhr = $.ajax({
          type: 'POST',
          url: action,
          data: form.serialize(),
          dataType: "script"
        });
      }, 1000);
    });
  })
</script>

app/views/dashboard/_recent_activity.html.erb
<div class="g_12">
  <div class="widget_header wwOptions">
    <h4 class="widget_header_title wwIcon i_16_data">Recent Activity</h4>
    <div class="w_Options i_16_settings">
    </div>
  </div>
  <div class="widget_contents noPadding">
    <table class="datatable tables">
      <thead>
        <tr>
          <th>Date</th>
          <th>Call or Text</th>
          <th>List(s)</th>
          <th>% Completed</th>
          <th>Cost</th>
          <th>View Progress</th>
        </tr>
      </thead>
      <tbody>
        <% @text_messages.each do |text_msg| %>
          <tr>
            <td>
              <%= text_msg.schedule_at.in_time_zone(current_user.time_zone).strftime("%b %d, %Y %H:%M") %>
            </td>
            <td style="text-align: center">
              Text
            </td>
            <td>
              <% text_msg.lists.collect{|l| l.name }.each do |list_name| %>
                <%= list_name %> <br/>
              <% end %>
            </td>
            <td style="text-align: center">
              <%= text_msg.percent_completed %>
            </td>
            <td style="text-align: right">
              <%= "$%.3f" % text_msg.total_cost %>
            </td>
            <td style="text-align: center">
              <%= link_to "View", text_msg, :class => "fancybox fancybox.ajax", :style => "color:#007BBF;" %>
            </td>
          </tr>
        <% end %>
        <% @calls.each do |call| %>
          <tr>
            <td>
              <%= call.schedule_at.in_time_zone(current_user.time_zone).strftime("%b %d, %Y %H:%M") %>
            </td>
            <td style="text-align: center">
              Call
            </td>
            <td>
              <% call.lists.collect{|l| l.name }.each do |list_name| %>
                <%= list_name %> <br/>
              <% end %>
            </td>
            <td style="text-align: center">
              <%= call.percent_completed %>
            </td>
            <td style="text-align: right">
              <%= "$%.3f" % call.total_cost %>
            </td>
            <td style="text-align: center">
              <%= link_to "View", call, :class => "fancybox fancybox.ajax", :style => "color:#007BBF;" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<style type="text/css">
  .dataTables_empty{
    text-align: center;
  }
</style>

app/views/dashboard/_walk_through.html.erb
<!-- Tip Content -->
<ol id="walk-through" style="display: none;">
  <li data-text="Start" class="custom">
    <p>
      Welcome to RoboCent! Would you like to take a brief tour?
    </p>
  </li>
  <li data-class="walk-point-1" data-button="Next: Inbox" data-options="tipLocation:right">
    <p>
      From the Dashboard, you can see real-time analytics of your texts and calls along with overall stats.
    </p>
  </li>
  <li data-class="walk-point-2" data-button="Next: Contacts" data-options="tipLocation:right">
    <p>
      On the Inbox page, you can receive text feedback and interact with individual contacts.
    </p>
  </li>
  <li data-class="walk-point-3" data-button="Next: Send a Text" data-options="tipLocation:right">
    <p>
      From the Contacts page, you can set-up contact lists, text-to-join keywords and upload contacts.
    </p>
  </li>
  <li data-class="walk-point-4" data-button="Next: Send a Call" data-options="tipLocation:right">
    <p>
      On Send a Text, you can send text blasts, set delivery options and   send test messages.
    </p>
  </li>
  <li data-class="walk-point-5" data-button="Next: Billing" data-options="tipLocation:right">
    <p>
      From Send a Call, you can record messages, set delivery options and send calls.
    </p>
  </li>
  <li data-class="walk-point-6" data-button="Next: Support" data-options="tipLocation:right">
    <p>
      You can change your billing information and view recent transactions on the Billing Page.
    </p>
  </li>
  <li data-class="walk-point-7" data-button="Close" data-options="tipLocation:right">
    <p>
      If you ever have any questions, view our video tutorials or use the live chat on the Support page!
    </p>
  </li>
</ol>

<script type="text/javascript">
  $(window).load(function() {
    $('#walk-through').joyride();
  });
</script>

app/views/dashboard/index.html.erb
<div class="g_6 contents_header">
  <h3 class="i_16_dashboard tab_label">Dashboard</h3>
</div>

<div class="g_12 separator">
  <span></span>
</div>

<%= render "shared/show_flash" %>

<div class="g_4">
  <div class="widget_header">
    <h4 class="widget_header_title wwIcon i_16_ui">Contacts</h4>
  </div>
  <div class="widget_contents noPadding">
    <table class="tables">
      <tbody>
        <tr>
          <td>Total Contacts</td>
          <td> <%= @total_contacts_count %> </td>
        </tr>
        <tr>
          <td>Texting Contacts</td>
          <td> <%= @text_contacts_count %> </td>
        </tr>
        <tr>
          <td>Calling Contacts</td>
          <td> <%= @call_contacts_count %> </td>
        </tr>
        <tr>
          <td colspan="2" style="text-align:center"> <%= link_to "Add and update contacts", contacts_path, :style => "color:#666666;" %> </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="g_4"></div>
<div class="g_4">
  <div class="widget_header">
    <h4 class="widget_header_title wwIcon i_16_tabs">Billing Summary</h4>
  </div>
  <div class="widget_contents noPadding">
    <table class="tables">
      <tbody>
        <tr>
          <td>Account Balance</td>
          <td> <%= "$%.3f" % current_user.current_balance %> </td>
        </tr>
        <tr>
          <td colspan="2" style="line-height:36px;"> You can send
            <%= @total_text_or_call_can_send %>
					texts or calls with this balance </td>
        </tr>
        <tr>
          <td colspan="2" style="text-align:center"> <%= link_to "Add Funds to your Account", billing_path, :style => "color:#666666;" %> </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div id="recent-activity-table">
  <%= render "recent_activity" %>
</div>

<% if current_user.pop_up_count == 0 %>
  <%= render "add_keyword_phone_number"%>
  <% current_user.pop_up_counter %>
<% elsif current_user.pop_up_count == 1 %>
  <%= render "walk_through" %>
  <% current_user.pop_up_counter %>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $("#recent-activity-table table.datatable thead tr th:first").click();
  })
</script>

app/views/dashboard/profile.html.erb
<div class="g_6 contents_header">
  <h3 class="i_16_login tab_label">Profile</h3>
</div>

<div class="g_12 separator"><span></span></div>

<%= render "shared/show_flash" %>

<div class="g_6">
  <div id="show-profile">
    <div class="widget_header">
      <h4 class="widget_header_title wwIcon i_16_valid" style="float:left">
        Profile Information
      </h4>
      <div style="float:right">
        <%= link_to "Edit", "#", :id => "profile-edit-button", :class => "simple_buttons", :style => "padding: 0 15px 0 15px;" %>
      </div>
      <div class="clear"></div>
    </div>
    <div class="widget_contents noPadding">
      <table class="tables">
        <tr>
          <td>Organization Name</td>
          <td>
            <%= @user.organization_name %>
          </td>
        </tr>
        <tr>
          <td>Organization Type</td>
          <td>
            <%= @user.organization_type %>
          </td>
        </tr>
        <tr>
          <td>Contact Name</td>
          <td>
            <%= @user.name %>
          </td>
        </tr>
        <tr>
          <td>Contact Email</td>
          <td>
            <%= @user.email %>
          </td>
        </tr>
        <tr>
          <td>Contact Phone</td>
          <td>
            <%= @user.phone %>
          </td>
        </tr>
        <tr>
          <td>Time Zone</td>
          <td>
            <%= @user.time_zone %>
          </td>
        </tr>
        <tr>
          <td>Your RoboCent Phone Number</td>
          <td>
            <% if @user.twilio_phone_number %>
              <%= formatted_number @user.twilio_phone_number.phone_number %>
            <% elsif @user.subscription.plan.recurring %>
              <span class="label">
                <%= link_to "Create Number", "javascript:;", :onclick => "$('#twilio-number-form').toggle();" %>
              </span>
            <% else %>
              <span class="label">
                Please upgrade your account to create Regular phone number.
              </span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div id="edit-profile" style="display:none">
    <div class="widget_header">
      <h4 class="widget_header_title wwIcon i_16_valid" style="float:left">
        Edit Profile Information
      </h4>
      <div style="float:right">
        <%= link_to "Close", "#", :id => "profile-close-button", :class => "simple_buttons", :style => "padding: 0 15px 0 15px;" %>
      </div>
      <div class="clear"></div>
    </div>
    <div class="widget_contents noPadding">
      <%= form_for(@user) do |f| %>
        <table class="tables">
          <tr>
            <td>Organization Name</td>
            <td>
              <%= f.text_field :organization_name, :class => "simple_field" %>
            </td>
          </tr>
          <tr>
            <td>Organization Type</td>
            <td>
              <%= f.select :organization_type, Organization::NAMES, {:prompt => "Select"}, :class => "simple_form" %>
            </td>
          </tr>
          <tr>
            <td>Contact Name</td>
            <td>
              <%= f.text_field :name, :class => "simple_field" %>
            </td>
          </tr>
          <tr>
            <td>Contact Email</td>
            <td>
              <%= f.text_field :email, :class => "simple_field", :required => true %>
            </td>
          </tr>
          <tr>
            <td>Contact Phone</td>
            <td>
              <%= f.text_field :phone, :class => "simple_field" %>
            </td>
          </tr>
          <tr>
            <td>Time Zone</td>
            <td>
              <%= f.select :time_zone, UsState::TIME_ZONES, { }, :class => "simple_form", :required => true %>
            </td>
          </tr>
          <tr>
            <td colspan="2" align="center">
              <%= f.submit "Update Profile", :class => "submitIt simple_buttons" %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

<div class="g_6">
  <div class="widget_header">
    <h4 class="widget_header_title wwIcon i_16_valid">
      Change Password
    </h4>
  </div>
  <div class="widget_contents noPadding">
    <%= form_for(@user, :url => update_password_path) do |f| %>
      <table class="tables">
        <tr>
          <td>Current Password</td>
          <td>
            <%= f.password_field :current_password, :class => "simple_field", :required => true %>
          </td>
        </tr>
        <tr>
          <td>New Password</td>
          <td>
            <%= f.password_field :password, :class => "simple_field", :required => true %>
          </td>
        </tr>
        <tr>
          <td colspan="2" align="center">
            <%= f.submit "Update Password", :class => "submitIt simple_buttons" %>
          </td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

<div class="g_6">
  <span class="label">
    <br/>
    You may edit your profile information at anytime. To view your billing information,
    add credits or change your account status, please visit the
    <%= link_to "billing page", billing_path %>.
    <br/><br/>
    To request a new RoboCent phone number, please email Info@RoboCent.com with your request.
  </span>
</div>

<% if current_user.subscription.plan.recurring and @user.twilio_phone_number.blank? %>
  <div class="g_12" id="twilio-number-form" style="display:none">
    <div class="widget_header">
      <h4 class="widget_header_title wwIcon i_16_valid">
        Create RoboCent Number
      </h4>
    </div>
    <div class="widget_contents noPadding">
      <div class="line_grid">
        <div class="g_12">
          <span class="label">
            To create a regular phone number, please enter the area code below.
          </span>
        </div>
      </div>
      <%= form_tag welcome_pop_up_submit_path, :method => :post, :id => "welcome-pop-up-form" do %>
        <%= fields_for TwilioPhoneNumber.new do |t| %>
          <div class="line_grid">
            <div class="g_2">
              <span class="label">Area Code : </span>
            </div>
            <div class="g_2">
              <div class="filed_error" id="error_list_name"></div>
              <%= t.text_field :area_code, :maxlength => "3", :class => "simple_field" %>
            </div>
            <div class="g_2">
              <div id="ajax-loader" style="width: 33px;">
                <%= image_tag("loading.gif", :style => "display:none") %>
              </div>
            </div>
            <div class="g_2">
              <span class="label">
                Select Number :
              </span>
            </div>
            <div class="g_4">
              <div class="filed_error" id="error_list_shortcode_keyword"></div>
              <span id="twilio_phone_number_select">
                <%= t.select :phone_number, "", {:prompt => "Select Number" }, :class => "simple_form" %>
              </span>
            </div>
          </div>
        <% end %>
        <div class="line_grid">
          <div class="g_4"></div>
          <div class="g_2">
            <%= submit_tag "Save Settings", :class => "submitIt simple_buttons" %>
          </div>
          <div class="g_2">
            <div class="ajax-loading" style="display:none">
              <%= image_tag("dashboard/Icons/Load/load-8.gif") %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $("#profile-edit-button").click(function(){
      $("#show-profile").hide();
      $("#edit-profile").show();
      return false;
    });
    $("#profile-close-button").click(function(){
      $("#edit-profile").hide();
      $("#show-profile").show();
      return false;
    });
  })
</script>

<style type="text/css">
  .simple_field{
    width: 200px;
  }
</style>