config/routes.rb
Robocent::Application.routes.draw do

  post "welcome-pop-up-submit" => 'dashboard#welcome_pop_up_submit', :as => :welcome_pop_up_submit

  resources :dnc, :only => [:index, :create, :destroy]

  match 'inbox-support'       => 'support#inbox',       :as => :inbox_support
  match 'send-a-call-support' => 'support#send_a_call', :as => :send_a_call_support
  match 'send-a-text-support' => 'support#send_a_text', :as => :send_a_text_support
  match 'dashboard-support'   => 'support#contacts',    :as => :contacts_support
  match 'support'             => 'support#index',       :as => :dashboard_support

  resources :password_resets, :except => [:index, :destroy]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "find-new-recording" => 'recordings#find_new_recording'
  match "replay"          => 'recordings#replay', :as => :replay
  match "save-or-record"  => 'recordings#save_or_record', :as => :save_or_record

  resources :incoming_calls

  resources :recordings do
    member do
      get :play
    end
  end

  match 'send-call'      => 'calls#new',            :as => :send_call
  match 'send-test-call' => 'calls#send_test_call', :as => :send_test_call

  resources :calls

  post "notifications/adaptive_ipn" => "notifications#adaptive_ipn"

  get "inbox"   => "sms_messages#inbox", :as => :inbox
  get "inbox-read" => "sms_messages#inbox_read"
  get "start-conversation" => 'sms_messages#start_conversation', :as => :start_conversation

  resources :sms_messages

  resources :text_messages, :only => [:show, :create] do
    member do
      get :send_text_succeeded_numbers
      get :send_text_errors
    end
  end

  #
  # Text
  #
  match 'send-a-test'         => 'text_messages#send_a_test', :as => :send_a_test
  match 'send-text'           => 'text_messages#new',         :as => :send_text

  put   "migrate"             => "subscriptions#migrate",   :as => :migrate
  match "migration"           => "subscriptions#migration", :as => :migration

  post 'stripe-webhook'       => 'stripe_webhook#create'

  put   'update-billing/:id'  => 'billing#update',       :as => :update_billing
  match 'edit-billing/:id'    => 'billing#edit',         :as => :edit_billing
  post  'fund-account'        => 'billing#fund_account', :as => :fund_account
  get   'billing'             => 'billing#index',           :as => :billing
  post  'billing'             => 'billing#create',          :as => :create_billing

  resources :imports do
    collection do
      get :save_s3_file_path
    end
    member do
      get :map_column
      match :insert_into_db
    end
  end

  resources :contacts

  resources :lists do
    member do
      get :export_contacts
    end
    collection do
      match :check_validation
    end
  end

  #
  # Dashboard
  #
  match 'profile'               => 'dashboard#profile',           :as => :profile
  match 'dashboard'             => 'dashboard#index',             :as => :dashboard

  #
  # user sessions
  #
  match 'login'                 => 'user_sessions#new',           :as => :login
  match 'logout'                => 'user_sessions#destroy',       :as => :logout

  resources :user_sessions, :only => [:create]

  #
  # registration
  #
  get   'twilionumbers/:code'      => 'users#twilionumbers',  :as => :twilionumbers
  match 'register/activate/:token' => 'users#activate',       :as => :activate

  put 'update-password'    => 'users#update_password',   :as => :update_password

  resources :users, :except => [:index, :show, :destroy]
  
  #
  # public pages
  #
  match "email-code"       => 'publics#email_code'
  match "email"       => 'publics#promo_email', :as => :promo_email
 
  match "smsterms"    => "publics#sms_terms", :as => :sms_terms
  match "smsprivacy"  => "publics#sms_privacy", :as => :sms_privacy
  match "terms"       => "publics#terms",      :as => "terms"
  match "privacy-policy" => "publics#privacy_policy", :as => :privacy_policy
  match 'contact-us-submit' => "publics#contact_us_submit" , :as => :contact_us_submit
  match "contact-us"  => "publics#contact",    :as => "contact_us"
  match 'solutions'   => "publics#solutions",  :as => "solutions"
  match 'residential-communities'   => "publics#residential_communities",  :as => "residential_communities"

  root :to => 'publics#index'
end

app/views/shared/_banner.html.erb
<div id="banner">
  <div id="content"><div id="content_inner">
      <!-- end intro -->
      <!-- end sidebar_right -->
      <ul id="slides1">
        <li>
          <div class="content_two">
            <%= image_tag "smarthost/banner_man.png", :alt => "", :border => "0", :class => "man" %>
            <div class="text">
              <p>The Most User Friendly</p>
              <h1>TEXT AND CALL PLATFORM</h1>
              <p>On The Market</p>
              <div class="buttons">
                <%= form_for User.new do |f| %>
                  <%= f.email_field :email, :placeholder => "Email", :class => "try-now-email" %>
                  <%= f.password_field :password, :placeholder => "Password", :class => "try-now-password" %>
                  <%= link_to "javascript:void(0);", :class => "small_btn-gry banner_two_btn left-mrgn", :onclick => "$(this).closest('form').submit();return false;" do %>
                    <span class="small_blk-gry">Try&nbsp;now</span>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/shared/_dashboard_footer.html.erb
<footer>
  <div class="wrapper">
    <span class="copyright">
      <a href="#" onClick="return SnapABug.startLink();" style="color: #B9B9B9">Live Chat 24 / 7</a>
    </span>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span class="copyright">
	Support: 757 821 2121
    </span>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span class="copyright">
	COPYRIGHT © 2012  | RoboCent, Inc.
    </span>
  </div>
</footer>

<!-- begin SnapEngage code -->
<script type="text/javascript">
  (function() {
    var se = document.createElement('script'); se.type = 'text/javascript'; se.async = true;
    se.src = '//commondatastorage.googleapis.com/code.snapengage.com/js/9843552f-3b65-481c-850a-78b1e037bb57.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(se, s);
  })();
</script>
<!-- end SnapEngage code -->

app/views/shared/_dashboard_header.html.erb
<header class="main_header">
  <div class="wrapper">
    <div class="logo">
      <%= link_to image_tag("next-logo.png"), dashboard_path %>
    </div>
    <div class="right-stat">
      <%  @calls = current_user.calls.find(:first, :select => "SUM(number_of_recipients) as total_call") %>
      <span class="col widget_header_title">
        <% @call_count =  @calls.present? ? @calls.total_call.to_i : 0 %>
        <%= pluralize(@call_count, "Call") %>
        Sent
      </span>
      <% @texts = current_user.text_messages.find(:first, :select => "SUM(number_of_texts_required) as total_text")  %>
      <% @sms_count = current_user.sms_messages.where(:status => "received").count %>
      <span class="col widget_header_title">
        <% @text_count =  @texts.present? ? (@texts.total_text.to_i + @sms_count) : 0 %>
        <%= pluralize(@text_count, "Texts") %>
        Sent
      </span>
    </div>
  </div>
</header>

<style type="text/css">
  .right-stat{
    float: right;
    width: 700px;
    padding-top: 25px;
    text-align: right;
  }

  .right-stat .col{
    float:right;
    text-align: right;
    padding-left: 30px;
    font-size: 20px;
  }
</style>

app/views/shared/_dashboard_side_bar_menu.html.erb
<aside class="sidebar">
  <ul class="tab_nav">
    <li class="i_32_dashboard <%= "active_tab" if current_page?(dashboard_path) %>">
      <%= link_to dashboard_path do %>
        <span class="tab_label walk-point-1">Dashboard</span>
      <% end %>
    </li>
    <li class="i_32_inbox <%= "active_tab" if current_page?(inbox_path) %>">
      <%= link_to inbox_path do %>
        <span class="tab_label walk-point-2">Inbox</span>
      <% end %>
    </li>
    <li class="i_32_ui <%= "active_tab" if controller_name == "contacts" %>">
      <%= link_to contacts_path do %>
        <span class="tab_label walk-point-3">Contacts</span>
      <% end %>
    </li>
    <li class="i_32_forms <%= "active_tab" if controller_name == "text_messages" %>">
      <%= link_to send_text_path do %>
        <span class="tab_label walk-point-4">Send a Text</span>
      <% end %>
    </li>
    <li class="i_32_ui <%= "active_tab" if controller_name == "calls" %>">
      <%= link_to send_call_path do %>
        <span class="tab_label walk-point-5">Send a Call</span>
      <% end %>
    </li>
    <li class="i_32_tables <%= "active_tab" if controller_name == "billing" %>">
      <%= link_to billing_path do %>
        <span class="tab_label walk-point-6">Billing</span>
      <% end %>
    </li>
    <li class="i_32_tables <%= "active_tab" if controller_name == "support" %>">
      <%= link_to dashboard_support_path do %>
        <span class="tab_label walk-point-7">Support</span>
      <% end %>
    </li>
  </ul>
</aside>

<style type="text/css">
  aside.sidebar .tab_nav > li {
    background-position: 10px 20px;
  }
</style>

app/views/shared/_dashboard_top_panel.html.erb
<div class="top_panel">
  <div class="wrapper">
    <div class="user">
      <%= link_to profile_path do %>
        <img src="/assets/dashboard/user_avatar.png" class="user_avatar" alt=""/>
        <span class="label">
          <% if current_user.present? %>
            <%= current_user.name.present? ? current_user.name : "Profile" %>
          <% end %>
        </span>
      <% end %>
    </div>
    <div class="top_links">
      <ul>
        <li class="small">
          <%= link_to logout_path do %>
            <span class="label">Log Out</span>
          <% end %>
        </li>
        <li class="small">
          <%= link_to billing_path do %>
            <span class="label">Balance
              <% if current_user.present? %>
                <%= "$%.3f" % current_user.current_balance %>
              <% end %>
            </span>
          <% end %>
        </li>
        <li class="i_22_ui">
          <%= link_to contacts_path do %>
            <span class="label">Contacts</span>
          <% end %>
        </li>
        <li class="i_22_inbox top_inbox">
          <%= link_to inbox_path do %>
            <span class="label lasCount">Inbox</span>
            <% @unread_messages_count = current_user.sms_messages.count(:all, :conditions => ["sms_messages.read = ? and status = ?", false, "received"])  %>
            <span class="small_count">
              <%= @unread_messages_count %>
            </span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

<style type="text/css">
  .top_links > ul > li.small > a {
    padding-left: 0px;
  }
</style>

app/views/shared/_google.html.erb
<script type="text/javascript">
  //Snap Engage Code
  (function() {
    var se = document.createElement('script');
    se.type = 'text/javascript';
    se.async = true;
    se.src = '//commondatastorage.googleapis.com/code.snapengage.com/js/9843552f-3b65-481c-850a-78b1e037bb57.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(se, s);
  })();
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32347443-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- Google Code for Remarketing tag -->
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">
  /* <![CDATA[ */
  var google_conversion_id = 990314665;
  var google_conversion_label = "p4YECM_J6gQQqYGc2AM";
  var google_custom_params = window.google_tag_params;
  var google_remarketing_only = true;
  /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
  <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/990314665/?value=0&amp;label=p4YECM_J6gQQqYGc2AM&amp;guid=ON&amp;script=0"/>
  </div>
</noscript>

app/views/shared/_payment_table.html.erb
<div id="content">
  <div class="table">
    <div class="container">
      <div class="table_sec first">
        <h2>Pay As You Go</h2>
        <div class="detail">
          <p>No Monthly Charge <br /><span class="month">&nbsp;</span></p>
          <ul>
            <li>2.0&cent; Per Text or Call</li>
            <li>1 Keyword</li>
            <li>Real Time Analytics</li>
            <li>No Credit Card Required</li>
            <li>250 Free Texts!</li>
          </ul>
          <%= link_to "", :class => "small_btn-gry table_btn pricing-plan-signup", :id => Plan::STRIPE_ID[0] do %>
            <span class="small_blk-gry">signup&nbsp;now</span>
          <% end %>
          <div class="clear"></div>
        </div>
        <%= image_tag "smarthost/table_bot.png", :alt => "", :border => "0" %>
      </div>



      <div class="table_sec">
        <h2 class="orange">Basic</h2>
        <div class="detail">
          <p>$5.00 <br /><span class="month">per month</span></p>
          <ul>
            <li>500 Texts or Calls Included</li>
            <li>3 Keywords</li>
            <li>Real Time Analytics</li>
            <li>1.5&cent; Per Additional Text or Call</li>
            <li>500 Free Texts!</li>
          </ul>
          <%= link_to "", :class => "small_btn-org table_btn pricing-plan-signup", :id => Plan::STRIPE_ID[1] do %>
            <span class="small_blk-org">signup&nbsp;now</span>
          <% end %>
          <div class="clear"></div>
        </div>
        <%= image_tag "smarthost/table_bot.png", :alt => "", :border => "0" %>
      </div>

      <div class="table_sec last">
        <h2>Advanced</h2>
        <div class="detail">
          <p>$19.00 <br /><span class="month">per month</span></p>
          <ul>
            <li>1,900 Texts or Calls Included</li>
            <li>5 Keywords</li>
            <li>Real Time Analytics</li>
            <li>1.3&cent; Per Additional Text or Call</li>
            <li>750 Free Texts!</li>
          </ul>
          <%= link_to "", :class => "small_btn-gry table_btn pricing-plan-signup", :id => Plan::STRIPE_ID[2] do %>
            <span class="small_blk-gry">signup&nbsp;now</span>
          <% end %>
          <div class="clear"></div>
        </div>
        <%= image_tag "smarthost/table_bot.png", :alt => "", :border => "0" %>
      </div>

    </div>
    <div class="clear"></div>
  </div>
</div>

app/views/shared/_pricing_table.html.erb
<div id="content" class="pricing-table">
	<div class="table">
		<div class="container">
			<div class="centered">
                        <% plans_last_element = @plans.length - 1 %>
			<% @plans.each_with_index do |plan, index| %>
				<div class="table_sec <%= 'last' if index == plans_last_element %>">
					<h2 class="<%= plan.amount > 0 ? 'orange' : nil %>"><%= plan.name %></h2>
					<div class="detail">
						<p>
							<% if plan.amount > 0 %>
								<%= number_to_currency(plan.monthly_fee) %><br /><span class="month">per month</span>
							<% else %>
								No Monthly Charge<br /><span class="month">&nbsp;</span>
							<% end %>
						</p>
						<ul>
							<li>
								<% if plan.amount > 0 %>
									<%= plan.monthly_included_text_or_call %> Texts or Calls Included
								<% else %>
									<%= "%.1f" % plan.price_per_call_or_text %>&cent; Per Text or Call
								<% end %>
							</li>
							<li>
								<%= pluralize(plan.max_keywords, "Keyword") %>
							</li>
							<li>
								Real Time Analytics
							</li>
							<li>
								<% if plan.amount > 0 %>
									<%= "%.1f" % plan.price_per_call_or_text %>&cent; Per Text or Call
								<% else %>
									No Credit Card Required
								<% end %>
								
							</li>
							<li>
								<%= plan.free_text %> Free Texts!
							</li>
						</ul>
						<%= link_to "", :class => "small_btn-gry table_btn pricing-plan-signup", :id => plan.stripe_id do %>
						<span class="small_blk-gry">signup&nbsp;now</span>
						<% end %>
						<div class="clear"></div>
					</div>
					<%= image_tag "smarthost/table_bot.png", :alt => "", :border => "0" %>
				</div>
				
			<% end %>
			</div>

		</div>
		<div class="clear"></div>
	</div>
</div>

app/views/shared/_public_flash.html.erb
<% if flash.present? %>
  <% if flash[:notice].present? %>
    <div class="container" id="flash" style="display:none">
      <div class="success iDialog">
        <%= flash[:notice] %>
      </div>
    </div>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="container" id="flash" style="display:none">
      <div class="warning iDialog">
        <%= flash[:alert] %>
      </div>
    </div>
  <% end %>

  <script type="text/javascript">
    $(document).ready(function(){
      $("#flash").delay(700).fadeIn(1500);
      
      $("#flash").click(function(){
        $("#flash").fadeOut(1500);
      });
    });
  </script>
<% end %>

app/views/shared/_public_header_home.html.erb
<div class="header header_mid" style="background-color:#343637; background-image:url(/assets/public_images/pattern_pixels.png)">
  <div class="header_inner">
    <!-- header slider -->
    <div class="header_slider">

      <div class="topSlider">

        <div class="oneByOne_slide">
          <div class="slide_image animate0 fadeInUp">
            <%= image_tag("public_images/temp/slider_img_1.png") %>
          </div>
          <div class="slide_text animate1 fadeInLeft">
            <div class="slide_title"><strong>Only the Best NOTIFICATION Solutions</strong></div>
            <div class="slide_description">
              <p>We provide <strong>Quality, Inexpensive Robocalls and Bulk Texting</strong> across the U.S.</p>
            </div>
          </div>
        </div>

        <div class="oneByOne_slide">
          <div class="slide_image animate0 fadeInDown">
            <%= image_tag("public_images/temp/slider_img_2.png") %>
          </div>
          <div class="slide_text animate0 fadeInRight">
            <div class="slide_title"><strong>Get Started NOW! Calls starting at 1.3¢</strong></div>
            <div class="slide_description">
              <p>Perfect for <strong>Emergency Notifications, Small Business Marketing, and Political Campaigns</strong></p>
            </div>
            <div class="slide_list">
              <ul>
                <li>Real-Time Results</li>
                <li>Straight-Forward Pricing</li>
                <li>Set Your own Caller ID</li>
                <li>24/7 Support</li>
                <li>No Hidden Fees</li>
                <li>"Text To Join" Included</li>
              </ul>
              <div class="clear"></div>
            </div>
          </div>
        </div>

        <div class="oneByOne_slide">
          <div class="slide_image">
            <%= image_tag("public_images/temp/slider_img_3.png") %>
          </div>
          <div class="slide_text">
            <div class="slide_title"><strong>Feature-Rich Operating System</strong></div>
            <div class="slide_description">
              <p>User-Friendly<strong>Solutions that Deliver</strong> Results</p>
            </div>
            <div class="slide_list">
              <ul>
                <li>Call-In Recording System</li>
                <li>Unlimited Texts/Calls</li>
                <li>Schedule Future Notifications</li>
                <li>Video Tutorials</li>
                <li>100% User-Controlled</li>
                <li>Free Live Chat</li>
                <li>Test Before Sending</li>
                <li>Custom Settings</li>
              </ul>
              <div class="clear"></div>
            </div>
          </div>
        </div>

        <div class="oneByOne_slide">
          <div class="slide_image">
            <%= image_tag("public_images/temp/slider_img_4.png") %>
          </div>
          <div class="slide_text">
            <div class="slide_title"><strong>Easy to use Dashboard</strong></div>
            <div class="slide_description">
              <p>Set-up and <strong>Monitor Your Calls and Texts</strong> in Real-Time.</p>
            </div>
          </div>
        </div>

      </div>
      <script type="text/javascript">
        jQuery(document).ready(function($) {
          $('.topSlider').oneByOne({
            className: 'oneByOne1',
            sliderClassName: 'oneByOne_slide',
            easeType: 'random',
            slideShow: true,
            width: 940,
            height: 429,
            slideShowDelay: 5000
          });
        });
      </script>
      <!--/ topSlider -->


    </div>
    <!--/ header slider -->
  </div>

</div>

app/views/shared/_public_top_nav.html.erb
<div id="header">
  <div class="top_sec">
    <div class="container">
      <ul>
        <li class="number">757 821 2121</li>
      </ul>
      <div class="buttons">
        <%= link_to "", "", :class => "chat", :onClick => "return SnapABug.startLink();" %>
        <div id="container">
          <div id="topnav" class="topnav">
            <%= link_to login_path, :class => "signin" do %>
              <span></span>
            <% end %>
          </div>
          <fieldset id="signin_menu">
            <%= form_tag user_sessions_path, :class => "loginform" do %>
              <p>
                <%= label_tag :email %>
                <%= text_field_tag :email, "", :tabindex => "4" %>
              </p>
              <p>
                <%= label_tag :password %>
                <%= password_field_tag :password, "", :tabindex => "5" %>
              </p>
              <p class="remember">
                <%= submit_tag "Login", :id => "signin_submit", :tabindex => "6" %>
                <%= check_box_tag :remember_me, 1, params[:remember_me], :tabindex => "7" %>
                <%= label_tag :remember_me %>
              </p>
              <p class="forgot">
                <%= link_to "Forgot your password?", new_password_reset_path, :id => "resend_password_link" %>
              </p>
            <% end %>
          </fieldset>
        </div>
      </div>
    </div>
  </div>
  <div class="main_bar">
    <div class="container">
      <%= link_to image_tag("next-logo.png", :alt => "", :border => "0", :class => "logo"), root_path %>
      <div class="navi">
        <ul id="menu">
          <li class="<%= 'selected' if current_page?(root_path) %>">
            <%= link_to "Home", root_path, :class => "#{'selected' if current_page?(root_path)}" %>
          </li>
          <li class="<%= 'selected' if current_page?(solutions_path) %>">
            <%= link_to "Solutions", solutions_path, :class => "#{'selected' if current_page?(solutions_path)}" %>
<%#*<ul>%>
<%#*<li>%>
<%#= link_to "Residential Communities", residential_communities_path  %>
<%#*</li>%>
<%#*</ul>%>
          </li>
          <li class="last <%= 'selected' if current_page?(contact_us_path) %>">
            <%= link_to "Contact Us", contact_us_path, :class => "#{'selected' if current_page?(contact_us_path)}" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/shared/_service.html.erb
<div class="services">
  <div class="container">
    <div class="service_sec">
      <%= image_tag "smarthost/system_admin.jpg", :alt => "", :border => "0" %>
      <h2>User-<span>Control</span></h2>
      <p>Users have complete control over the RoboCent system, including the content of the messages, sending options and recipients.</p>
    </div>

    <div class="service_sec">
      <%= image_tag "smarthost/backup.jpg", :alt => "", :border => "0" %>
      <h2><span>Cloud</span> Based</h2>
      <p>RoboCent is completely cloud-based, ensuring 99.9% uptime, an extremely reliable sending platform and enhanced ease-of-use.</p>
    </div>

    <div class="service_sec last">
      <%= image_tag "smarthost/live_support.jpg", :alt => "", :border => "0" %>
      <h2><span>Live</span> Support</h2>
      <p>The RoboCent team is available via live chat, phone or email 7 days a week to ensure you can send your messages with ease.</p>
    </div>

  </div>
  <div class="clear"></div>
</div>

app/views/shared/_show_flash.html.erb
<% if flash.present? %>
  <% if flash[:notice].present? %>
    <div class="g_12" id="flash" style="display:none">
      <div class="success iDialog">
        <%= flash[:notice] %>
      </div>
    </div>
  <% end %>
  <% if flash[:alert].present? %>
    <div class="g_12" id="flash" style="display:none">
      <div class="alert iDialog">
        <%= flash[:alert] %>
      </div>
    </div>
  <% end %>
  <% if flash[:error].present? %>
    <div class="g_12" id="flash" style="display:none">
      <div class="error iDialog">
        <%= flash[:error] %>
      </div>
    </div>
  <% end %>

  <script type="text/javascript">
    $(document).ready(function(){
      $("#flash").delay(500).fadeIn(1500);
      $("#flash").delay(3000).fadeOut(1500);
    });
  </script>
<% end %>

app/views/shared/_sign_up_popup.erb
<div id="new-user-signup">
  <%= form_for User.new, :html => {:class => "new-user-popup"} do |f| %>
    <div class="warning" style="display:none"></div>
    <%= hidden_field_tag "pricing_plan", "" %>
    <br />
    <%= f.email_field :email, :placeholder => "Email", :class => "try-now-email" %>
    <br />
    <br />
    <%= f.password_field :password, :placeholder => "Password", :class => "try-now-password" %>
    <br /><br/>
    <span>
      By clicking on the "NEXT" button, you agree that you have read, understand, and accept the
      <%= link_to "Terms & Conditions", terms_path, :target => "_blank" %>
    </span>
    <br /><br/>
    <%= link_to "javascript:void(0);", :class => "small_btn-org banner_two_btn left-mrgn", :onclick => "$(this).closest('form').submit();return false;" do %>
      <span class="small_blk-org">Next >></span>
    <% end %>
  <% end %>
</div>

<% content_for :js do %>
  <script type="text/javascript">
    jQuery(document).ready( function(){
      $myWindow = jQuery('#new-user-signup');

      $('.sign-up-popup').live( "clickoutside", function(event){
        $myWindow.dialog('close');
      });

      $('document').ready(function(){
        $('.pricing-plan-signup').click(function(){
          $myWindow.dialog('open');
          var pricing_plan_id = this.id;
          $('#new-user-signup #pricing_plan').val(pricing_plan_id);
          return false;
        });
        $('.signup-popup').click(function(){
          $myWindow.dialog('open');
          return false;
        });
      });

      $myWindow.dialog({
        beforeClose :function(event,ui){
          return true;
          $('#new_user #pricing_plan').val('0');
        },
        open :function( event, ui ){
          $('.ui-widget-overlay').bind('click', function() {
            $myWindow.dialog('close');
          });
        },
        close :function( event, ui ){
          $("#new_user.new-user-popup .warning").hide();
        },
        title: "Signup Now",
        resizable: false,
        draggable: false,
        height: 350,
        width: '400px',
        modal: true,
        position: ['middle',80],
        closeText: "X",
        dialogClass: "sign-up-popup",
        hide: "scale",
        show: "scale",
        autoOpen: false,
        overlay: {
          opacity: 0.8
        }
      });
    });

    jQuery(document).ready( function(){
      $("#new_user.new-user-popup").submit(function(e){
        var email = $("#new_user.new-user-popup #user_email").val();
        var password = $("#new_user.new-user-popup #user_password").val();
        var email_regex = /^[\w\.\+-]{1,}\@([\da-zA-Z-]{1,}\.){1,}[\da-zA-Z-]{2,6}$/i
        var errors = "";
        if(!email_regex.test(email)){
          errors += "<li>Email is Invalid</li>";
        }
        if(password.length < 6){
          errors += "<li>Password must be at least 6 characters long</li>"
        }

        if(errors != ""){
          e.preventDefault();
          $("#new_user.new-user-popup .warning").html("<ul>"+errors+"</ul>");
          $("#new_user.new-user-popup .warning").show();
        }
        else{
          return true;
        }
      });
    });
    
  </script>
<% end %>