config/routes.rb
Robocent::Application.routes.draw do

  post "welcome-pop-up-submit" => 'dashboard#welcome_pop_up_submit', :as => :welcome_pop_up_submit

  resources :dnc, :only => [:index, :create, :destroy]

  match 'inbox-support'       => 'support#inbox',       :as => :inbox_support
  match 'send-a-call-support' => 'support#send_a_call', :as => :send_a_call_support
  match 'send-a-text-support' => 'support#send_a_text', :as => :send_a_text_support
  match 'dashboard-support'   => 'support#contacts',    :as => :contacts_support
  match 'support'             => 'support#index',       :as => :dashboard_support

  resources :password_resets, :except => [:index, :destroy]

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "find-new-recording" => 'recordings#find_new_recording'
  match "replay"          => 'recordings#replay', :as => :replay
  match "save-or-record"  => 'recordings#save_or_record', :as => :save_or_record

  resources :incoming_calls

  resources :recordings do
    member do
      get :play
    end
  end

  match 'send-call'      => 'calls#new',            :as => :send_call
  match 'send-test-call' => 'calls#send_test_call', :as => :send_test_call

  resources :calls

  post "notifications/adaptive_ipn" => "notifications#adaptive_ipn"

  get "inbox"   => "sms_messages#inbox", :as => :inbox
  get "inbox-read" => "sms_messages#inbox_read"
  get "start-conversation" => 'sms_messages#start_conversation', :as => :start_conversation

  resources :sms_messages

  resources :text_messages, :only => [:show, :create] do
    member do
      get :send_text_succeeded_numbers
      get :send_text_errors
    end
  end

  #
  # Text
  #
  match 'send-a-test'         => 'text_messages#send_a_test', :as => :send_a_test
  match 'send-text'           => 'text_messages#new',         :as => :send_text

  put   "migrate"             => "subscriptions#migrate",   :as => :migrate
  match "migration"           => "subscriptions#migration", :as => :migration

  post 'stripe-webhook'       => 'stripe_webhook#create'

  put   'update-billing/:id'  => 'billing#update',       :as => :update_billing
  match 'edit-billing/:id'    => 'billing#edit',         :as => :edit_billing
  post  'fund-account'        => 'billing#fund_account', :as => :fund_account
  get   'billing'             => 'billing#index',           :as => :billing
  post  'billing'             => 'billing#create',          :as => :create_billing

  resources :imports do
    collection do
      get :save_s3_file_path
    end
    member do
      get :map_column
      match :insert_into_db
    end
  end

  resources :contacts

  resources :lists do
    member do
      get :export_contacts
    end
    collection do
      match :check_validation
    end
  end

  #
  # Dashboard
  #
  match 'profile'               => 'dashboard#profile',           :as => :profile
  match 'dashboard'             => 'dashboard#index',             :as => :dashboard

  #
  # user sessions
  #
  match 'login'                 => 'user_sessions#new',           :as => :login
  match 'logout'                => 'user_sessions#destroy',       :as => :logout

  resources :user_sessions, :only => [:create]

  #
  # registration
  #
  get   'twilionumbers/:code'      => 'users#twilionumbers',  :as => :twilionumbers
  match 'register/activate/:token' => 'users#activate',       :as => :activate

  put 'update-password'    => 'users#update_password',   :as => :update_password

  resources :users, :except => [:index, :show, :destroy]
  
  #
  # public pages
  #
  match "email-code"       => 'publics#email_code'
  match "email"       => 'publics#promo_email', :as => :promo_email
 
  match "smsterms"    => "publics#sms_terms", :as => :sms_terms
  match "smsprivacy"  => "publics#sms_privacy", :as => :sms_privacy
  match "terms"       => "publics#terms",      :as => "terms"
  match "privacy-policy" => "publics#privacy_policy", :as => :privacy_policy
  match 'contact-us-submit' => "publics#contact_us_submit" , :as => :contact_us_submit
  match "contact-us"  => "publics#contact",    :as => "contact_us"
  match 'solutions'   => "publics#solutions",  :as => "solutions"
  match 'residential-communities'   => "publics#residential_communities",  :as => "residential_communities"

  root :to => 'publics#index'
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  before_filter :require_login

  layout 'dashboard'

  def index
    @current_balance = current_user.current_balance
    @subscribed_plan = current_user.subscription.plan
    @monthly_charge = @subscribed_plan.amount.to_f / 100.0
    @price_per_call_or_text = @subscribed_plan.price_per_call_or_text.to_f / 100.0
    @total_call_can = (@current_balance.to_f / @price_per_call_or_text.to_f ).to_i
    @billing_setting = current_user.billing_setting
    @funds = current_user.receipts.where({:free => nil, :debit => "0"})

    Time.zone = current_user.time_zone
    if params[:date_from].present? && params[:date_to].present?
      @date_from = Time.zone.parse(params[:date_from].to_date.to_s).beginning_of_day.utc
      @date_to = Time.zone.parse(params[:date_to].to_date.to_s).end_of_day.utc
    else
      @date_from = Time.zone.now.beginning_of_month.utc
      @date_to = Time.zone.now.end_of_day.utc
    end
    Time.zone = "UTC"

    @transactions = current_user.receipts.by_date_range(@date_from, @date_to).order("id desc")
    if @transactions.present?
      @beginning_balance = @transactions.last.current_balance - @transactions.last.credit + @transactions.last.debit
      @total_debits = @transactions.sum(:debit)
      @total_credits = @transactions.sum(:credit)
      @total_change = (@total_credits - @total_debits).abs
      @ending_balance = @transactions.first.current_balance
    end
  end

  def fund_account
    if current_user.billing_setting.charge(params[:amount], "Manually funded account")
      @current_balance = current_user.current_balance
      @price_per_call_or_text = current_user.subscription.plan.price_per_call_or_text
      @total_call_can = (@current_balance / (@price_per_call_or_text / 100 )).to_i
    end
  end

  def create
    begin
      @billing_setting = current_user.billing_setting
      if @billing_setting.present?
        @billing_setting.update_attributes(params[:billing_setting])
        flash[:notice] = "Successfully updated your billing information"
      else
         @billing_setting = current_user.build_billing_setting(params[:billing_setting])
         flash[:notice] = "Successfully updated your billing information" if @billing_setting.save
      end
    rescue Stripe::StripeError => e
      logger.error e.message
      flash[:alert] = e.message
    end
    redirect_to request.referer
  end

  def edit
    @billing_setting = BillingSetting.find(params[:id])
    render :layout => false
  end

  def update
    begin
      @billing_setting = current_user.billing_setting
      @billing_setting.update_attributes(params[:billing_setting])
      redirect_to billing_path, :notice => "Successfully updated your billing information"
    rescue Stripe::StripeError => e
      logger.error e.message
      redirect_to billing_path, :alert => e.message
    end
  end
end

app/views/billing/_account_info.html.erb
<div class="widget_header">
  <h4 class="widget_header_title wwIcon i_16_valid">
    Account Information
  </h4>
</div>
<div class="widget_contents noPadding">
  <table class="tables">
    <tr>
      <td>Account Balance</td>
      <td style="text-align: right">
        <span id="current-balance">
          $<%= "%.3f" % @current_balance %>
        </span>
      </td>
    </tr>
    <tr>
      <td style="line-height: 36px;">Calls or Texts that can be Sent with this Balance</td>
      <td style="text-align: right">
        <span id="total-call-can">
          <%= @total_call_can %>
        </span>
      </td>
    </tr>
    <tr>
      <td>Price per Call or Text</td>
      <td style="text-align: right">
        $<%= "%.3f" % @price_per_call_or_text %>
      </td>
    </tr>
    <tr>
      <td>Monthly Charge</td>
      <td style="text-align: right">
        $<%= "%.3f" % @monthly_charge %>
      </td>
    </tr>
  </table>
</div>

app/views/billing/_add_funds_form.html.erb
<div class="g_12">
  <h4 class="widget_header_title">
    By submitting this form, it will charge your payment method immediately.
  </h4>
</div>
<div class="g_12">
  <div class="widget_contents noPadding">
    <%= form_tag fund_account_path, :id => "fund-account-form" do %>
      <div class="line_grid">
        <div class="g_3" style="text-align:right">
          <span class="label">$</span>
        </div>
        <div class="g_9">
          <%= text_field_tag :amount, "", :class => "simple_field" %>
        </div>
      </div>
      <div class="line_grid">
        <div class="g_3"></div>
        <div class="g_9">
          <%= submit_tag "Add Fund", :class => "submitIt simple_buttons" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/billing/_edit.html.erb
<div class="widget_header">
  <h4 class="widget_header_title wwIcon i_16_valid" style="float:left">
    Edit Billing Information
  </h4>
  <div style="float:right">
    <%= link_to "Close", "#", :id => "billing-close-button", :class => "simple_buttons", :style => "padding: 0 15px 0 15px;" %>
  </div>
  <div class="clear"></div>
</div>
<div class="widget_contents noPadding">
  <div id="credit-card-errors" style="display: none">
    <div id="stripe-error-message" class="alert iDialog"></div>
  </div>
  <%= form_for(@billing_setting, :url => update_billing_path(@billing_setting)) do |f| %>
    <%= f.hidden_field :stripe_token %>
    <%= f.hidden_field :card_last_four_digits %>
    <%= f.hidden_field :card_exp_month %>
    <%= f.hidden_field :card_exp_year %>
    <%= f.hidden_field :card_type %>

    <table class="tables">
      <thead>
        <tr>
          <td>Card Holder Name<span class="must">*</span></td>
          <td>
            <%= f.text_field :card_holder_name, :class => "simple_field", :required => true %>
          </td>
        </tr>
      </thead>
      <tbody id="credit-card">
        <tr>
          <td>Card Number<span class="must">*</span></td>
          <td>
            <%= text_field_tag :credit_card_number, "", :class => "simple_field", :disabled => true, :required => true %>
          </td>
        </tr>
        <tr>
          <td>Card Security Code<span class="must">*</span></td>
          <td>
            <%= text_field_tag :cvv, "", :class => "simple_field", :disabled => true, :required => true %>
          </td>
        </tr>
        <tr>
          <td>Expiration Date<span class="must">*</span></td>
          <td>
            <%= date_select "", :expiry_date, {:discard_day => true, :order => [:month, :year], :use_month_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year + 25, :disabled => true}, {:class => 'small'} %>
          </td>
        </tr>
        <tr>
          <td colspan="2" align="center">
            <%= f.submit :class => "submitIt simple_buttons" %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

<style type="text/css">
  .simple_field{
    width: 200px;
  }
</style>

app/views/billing/_form.html.erb
<div class="g_12">
  <div class="contents_header">
    <h3 class="widget_header_title" style="margin-bottom: 20px;">
      <% if !current_user.subscription.plan.recurring %>
        In order to send a text or call, you must have a credit card on file.
      <% elsif current_user.subscription.trial %>
        In order to send a text or call, you must have a credit card on file.
        If you cancel your account by
        <%= current_user.subscription.trial_end.in_time_zone(current_user.time_zone).strftime("%B %d, %Y %I:%M %p") if current_user.subscription.trial_end.present? %>,
        your card will not be charged.
      <% else %>
        Your <%= current_user.subscription.plan.trial_period_days %>
        day free trial has ended! Please enter your billing information below
        to gain access to your account. You will only be billed
        <%= "$%.3f" % (current_user.subscription.plan.amount.to_f / 100.0) %>
        per month!
      <% end %>
    </h3>
  </div>
  <div class="clear"></div>
  <div class="widget_contents noPadding">
    <div id="credit-card-errors" style="display: none">
      <div id="stripe-error-message" class="alert iDialog"></div>
    </div>
    <%= form_for(@billing_setting ||= BillingSetting.new, :url => create_billing_path) do |f| %>
      <%= f.hidden_field :stripe_token %>
      <%= f.hidden_field :card_last_four_digits %>
      <%= f.hidden_field :card_exp_month %>
      <%= f.hidden_field :card_exp_year %>
      <%= f.hidden_field :card_type %>

      <div class="line_grid">
        <div class="g_3">
          <span class="label">Name on Card<span class="must">*</span></span>
        </div>
        <div class="g_9">
          <%= f.text_field :card_holder_name, :class => "simple_field", :required => true %>
        </div>
      </div>

      <div id="credit-card">
        <div class="line_grid">
          <div class="g_3">
            <span class="label">Credit Card Number<span class="must">*</span></span>
          </div>
          <div class="g_9">
            <%= text_field_tag :credit_card_number, "", :class => "simple_field", :disabled => true, :required => true %>
          </div>
        </div>

        <div class="line_grid">
          <div class="g_3">
            <span class="label">Exp. Date<span class="must">*</span></span>
          </div>
          <div class="g_9">
            <%= date_select "", :expiry_date, {:discard_day => true, :order => [:month, :year], :use_month_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year + 25, :disabled => true}, {:class => 'small simple_form'} %>
          </div>
        </div>

        <div class="line_grid">
          <div class="g_3">
            <span class="label">CVV Code<span class="must">*</span></span>
          </div>
          <div class="g_9">
            <%= text_field_tag :cvv, "", :class => "simple_field", :disabled => true, :required => true %>
          </div>
        </div>

        <div class="line_grid">
          <div class="g_3"></div>
          <div class="g_9">
            <%= f.submit :class => "submitIt simple_buttons" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="clear"></div>

app/views/billing/_show.html.erb
<div class="widget_header">
  <h4 class="widget_header_title wwIcon i_16_valid" style="float:left">
    Billing Information
  </h4>
  <div style="float:right">
    <%= link_to "Edit", "#", :id => "billing-edit-button", :class => "simple_buttons", :style => "padding: 0 15px 0 15px;" %>
  </div>
  <div class="clear"></div>
</div>
<div class="widget_contents noPadding">
  <table class="tables">
    <tr>
      <td>Card Holder Name</td>
      <td>
        <%= @billing_setting.card_holder_name %>
      </td>
    </tr>
    <tr>
      <td>Card Number</td>
      <td>
        <%= "*********#{@billing_setting.card_last_four_digits}" if @billing_setting.card_last_four_digits.present? %>
      </td>
    </tr>
    <tr>
      <td>Card Expiration</td>
      <td>
        <%= @billing_setting.card_expiry_date.strftime("%B %d, %Y") if @billing_setting.card_expiry_date.present? %>
      </td>
    </tr>
    <tr>
      <td>Card Type</td>
      <td>
        <%= @billing_setting.card_type %>
      </td>
    </tr>
    <tr>
      <td>Last Updated</td>
      <td><%= @billing_setting.updated_at.in_time_zone(current_user.time_zone).strftime("%b %d, %Y %H:%M") if @billing_setting.card_last_four_digits.present? %></td>
    </tr>
  </table>
</div>

app/views/billing/_transactions.html.erb
<div class="g_12" id="table_wTabs">
  <div class="widget_header wwOptions">
    <h4 class="widget_header_title wwIcon i_16_tabs">Transactions</h4>
    <ul class="w_Tabs">
      <li><a href="#table_wTabs-1" title="Tab 1">Monthly</a></li>
      <li><a href="#table_wTabs-2" title="Tab 2">Funds</a></li>
    </ul>
  </div>
  <div class="widget_contents noPadding">
    <div id="table_wTabs-2">
      <table class="tables <%= "datatable" if @funds.present? %>" id="">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
          </tr>
        </thead>
        <tbody>
          <% if @funds.present? %>
            <% @funds.each do |fund| %>
              <tr>
                <td>
                  <%= fund.created_at.in_time_zone(current_user.time_zone).strftime("%b %d, %Y %H:%M") %>
                </td>
                <td>
                  <%= fund.memo %>
                </td>
                <td style="text-align: right">
                  <%= "%.3f" % fund.credit unless fund.credit.zero? %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="3" style="text-align:center">
                No Records Found.
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if @funds.present? %>
        <div class="g_12">
          <h4 class="widget_header_title">
            Total Funded ( From
            <%= @funds.first.created_at.in_time_zone(current_user.time_zone).strftime("%B %d, %Y") %>
            To <%= @funds.last.created_at.in_time_zone(current_user.time_zone).strftime("%B %d, %Y") %>
            ) :
            $<%= "%.3f" % @funds.sum(:credit) %>
          </h4>
        </div>
      <% end %>
    </div>
    <div id="table_wTabs-1">
      <div class="g_12">
        <form action="" method="get" id="tx_by_date">
          <span class="label">From</span>
          <%= text_field_tag :date_from, @date_from.in_time_zone(current_user.time_zone).strftime("%B %d, %Y"), :class => "simple_field" %>
          <span class="label">To</span>
          <%= text_field_tag :date_to, @date_to.in_time_zone(current_user.time_zone).strftime("%B %d, %Y"), :class => "simple_field" %>
          <%= link_to 'Go', "javascript:document.getElementById('tx_by_date').submit();", :class => 'submitIt simple_buttons' %>
        </form>
      </div>
      <div class="clear"></div>
      <table class="tables" id="">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Debits</th>
            <th>Credits</th>
            <th>Balance</th>
          </tr>
        </thead>
        <tbody>
          <% if @transactions.present? %>
            <% @transactions.each do |tx| %>
              <tr>
                <td>
                  <%= tx.created_at.in_time_zone(current_user.time_zone).strftime("%b %d, %Y %H:%M") %>
                </td>
                <td>
                  <%= tx.memo %>
                </td>
                <td style="text-align: right">
                  <%= "%.3f" % tx.debit unless tx.debit.zero? %>
                </td>
                <td style="text-align: right">
                  <%= "%.3f" % tx.credit unless tx.credit.zero? %>
                </td>
                <td style="text-align: right">
                  <%= "%.3f" % tx.current_balance %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="5" style="text-align:center">
                No Records Found.
              </td>
            </tr>
          <% end %>
          <tr>
            <td colspan="5" height="15"></td>
          </tr>
        </tbody>
      </table>
      <% if @transactions.present? %>
      <div class="g_6"></div>
        <div class="g_6">
          <table class="tables">
            <tbody>
              <tr>
                <td colspan="2" style="text-align: left">
                  Statement Period :
                  <%= @date_from.in_time_zone(current_user.time_zone).strftime("%b %d, %Y") %>
                  to
                  <%= @date_to.in_time_zone(current_user.time_zone).strftime("%b %d, %Y") %>
                </td>
              </tr>
              <tr>
                <td style="text-align: right">
                  Beginning Balance
                </td>
                <td style="text-align: right">
                  $<%= "%.3f" % @beginning_balance %>
                </td>
              </tr>
              <tr>
                <td style="text-align: right">
                  Total Credits
                </td>
                <td style="text-align: right">
                  $<%= "%.3f" % @total_credits %>
                </td>
              </tr>
              <tr>
                <td style="text-align: right">
                  Total Debits
                </td>
                <td style="text-align: right">
                  $<%= "%.3f" % @total_debits %>
                </td>
              </tr>
              <tr>
                <td style="text-align: right">
                  Total Change
                </td>
                <td style="text-align: right">
                  $<%= "%.3f" % @total_change %>
                </td>
              </tr>
              <tr>
                <td style="text-align: right">
                  Ending Balance
                </td>
                <td style="text-align: right">
                  $<%= "%.3f" % @ending_balance %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/billing/fund_account.js.erb
<% if @current_balance.present? %>
 $("#current-balance").html("<%= "$%.3f" % @current_balance %>");
 $("#total-call-can").html("<%= @total_call_can %>");
<% end %>

$("#billing .ajax-loading").hide();

app/views/billing/index.html.erb
<div class="g_6 contents_header">
  <h3 class="i_16_tables tab_label">Billing</h3>
</div>
<div class="g_2" id="billing">
  <div class="ajax-loading" style="display:none">
    <%= image_tag("dashboard/Icons/Load/load-8.gif") %>
  </div>
</div>
<div class="g_2">
  <%= link_to "Upgrade/Downgrade", migration_path, :class => "simple_buttons contact-button" %>
</div>
<div class="g_2">
  <%= link_to "Add Funds", "#", :class => "simple_buttons contact-button", :id => "new_list_link" %>
</div>

<div class="g_12 separator"><span></span></div>

<%= render "shared/show_flash" %>

<div class="g_6">
  <div id="show-billing">
    <%= render "show" %>
  </div>
  <div id="edit-billing" style="display:none">
    <%= render "edit" %>
  </div>
</div>

<div class="g_6">
  <%= render "account_info" %>
</div>

<div class="g_12 separator"><span></span></div>


<%= render "transactions" %>

<div id="dialog" title="Add Funds">
  <div class="dialog">
    <%= render "add_funds_form" %>
  </div>
</div>

<script type="text/javascript">
  $(function(){
    $(".edit_billing_setting select").uniform();
    
    $("#fund-account-form").submit(function(){
      var amount = parseFloat($("#fund-account-form #amount").val());
      if(amount >= 0.5)
      {
        var action = $(this).attr("action");
        $.ajax({
          type: 'POST',
          url: action,
          data: $(this).serialize(),
          dataType: "script"
        });
        $("#billing .ajax-loading").show();
        $("#dialog").dialog("close");
      }
      else
      {
        alert("Amount can't be less than $0.5 !");
      }
      return false;
    });

    $("#billing-edit-button").click(function(){
      $("#show-billing").hide();
      $("#edit-billing").show();
      return false;
    });
    $("#billing-close-button").click(function(){
      $("#edit-billing").hide();
      $("#show-billing").show();
      return false;
    });

  });

  window.onload = function() {
    var myCalendar1 = new dhtmlXCalendarObject(["date_from"]);
    myCalendar1.setDateFormat("%F %d, %Y");
    myCalendar1.hideTime();
    myCalendar1.setSkin('omega');
    var myCalendar2 = new dhtmlXCalendarObject(["date_to"]);
    myCalendar2.setDateFormat("%F %d, %Y");
    myCalendar2.hideTime();
    myCalendar2.setSkin('omega');
  };
</script>